In [35]:
import pandas as pd
import datetime as dt

In [36]:
weather = pd.read_csv('weather_alerts_grouped.csv')
weather['END_DATETIME'] = pd.to_datetime(weather['END_DATETIME'])
weather['BEGIN_DATETIME'] = pd.to_datetime(weather['BEGIN_DATETIME'])

In [37]:
crime = pd.read_csv('PropertyCrimes_CLEAN.csv')
crime['Incident_datetime'] = pd.to_datetime(crime['Incident_datetime'])

In [38]:
#extract date from datetime for both crimes and weather
weather['DATE'] = weather['BEGIN_DATETIME'].dt.date
crime['DATE'] = crime['Incident_datetime'].dt.date

In [39]:
crime_weather = pd.merge(crime, weather, on='DATE', how='left')
crime_weather[crime_weather['EVENT_TYPE'].notnull()]

,Complaint_No,Property_Crimes,Location_Type,Zipcode,Property_No,Property_type,Property_Desc,2010 Pop,Workforce Growth,ID Gender,...,BEGIN_DATETIME,END_DATETIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,time_diff,EVENT_TYPE_col,date.1,weather_id
905,20120621122401,Motor Vehicle Theft,Parking Lot,28217,1.0,Automobile,Vehicles and Parts,24199,NaN,NaN,...,2012-05-22 21:30:00,2012-05-22 21:45:00,35.150000,-80.885000,35.150000,-80.885000,0 days 00:15:00,Lightning,2012-05-22,58.0
906,20120621122401,Motor Vehicle Theft,Parking Lot,28217,1.0,Automobile,Vehicles and Parts,24199,NaN,NaN,...,2012-05-22 21:30:00,2012-05-22 21:45:00,35.150000,-80.885000,35.150000,-80.885000,0 days 00:15:00,Lightning,2012-05-22,58.0
2568,20120701013000,Burglary/B&E,Outdoors,28215,1.0,Windows,Structures,53629,NaN,NaN,...,2012-07-01 17:35:00,2012-07-01 17:51:00,35.133333,-80.740767,35.133333,-80.740767,0 days 00:16:00,Hail,2012-07-01,30.0
2569,20120701013000,Burglary/B&E,Outdoors,28215,1.0,Windows,Structures,53629,NaN,NaN,...,2012-07-01 17:30:00,2012-07-01 17:45:00,35.340000,-80.810000,35.340000,-80.810000,0 days 00:15:00,Lightning,2012-07-01,59.0
2570,20120701013000,Burglary/B&E,Outdoors,28215,1.0,Windows,Structures,53629,NaN,NaN,...,2012-07-01 17:21:00,2012-07-01 17:40:00,35.320000,-80.800000,35.180000,-80.655000,0 days 00:19:00,Thunderstorm Wind,2012-07-01,82.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196169,20161202144902,Burglary/B&E,Other,28203,2.0,Tools (Power and Hand),Miscellaneous,11315,NaN,NaN,...,2016-11-30 18:26:00,2016-11-30 18:29:00,35.124000,-80.953000,35.143000,-80.918000,0 days 00:03:00,Tornado,2016-11-30,135.0
196170,20161202144902,Burglary/B&E,Other,28203,3.0,Tools (Power and Hand),Miscellaneous,11315,NaN,NaN,...,2016-11-30 18:26:00,2016-11-30 18:29:00,35.124000,-80.953000,35.143000,-80.918000,0 days 00:03:00,Tornado,2016-11-30,135.0
196171,20161202144902,Burglary/B&E,Other,28203,4.0,Other,Other Property,11315,NaN,NaN,...,2016-11-30 18:26:00,2016-11-30 18:29:00,35.124000,-80.953000,35.143000,-80.918000,0 days 00:03:00,Tornado,2016-11-30,135.0
196728,20161208094902,Shoplifting,Indoors,28273,1.0,Other,Other Property,31478,NaN,NaN,...,2016-11-30 18:26:00,2016-11-30 18:29:00,35.124000,-80.953000,35.143000,-80.918000,0 days 00:03:00,Tornado,2016-11-30,135.0
196867,20161209130000,Embezzlement,Indoors,28210,1.0,Money/Cash,Money and Securities,42256,NaN,NaN,...,2016-11-30 18:26:00,2016-11-30 18:29:00,35.124000,-80.953000,35.143000,-80.918000,0 days 00:03:00,Tornado,2016-11-30,135.0

In [40]:
crime_weather

,Complaint_No,Property_Crimes,Location_Type,Zipcode,Property_No,Property_type,Property_Desc,2010 Pop,Workforce Growth,ID Gender,...,BEGIN_DATETIME,END_DATETIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,time_diff,EVENT_TYPE_col,date.1,weather_id
0,20120616144400,Theft of Motor Vehicle Parts from Vehicle,Parking Lot,28205,1.0,Vehicle Tag,Vehicles and Parts,43931,NaN,NaN,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20120616144400,Theft of Motor Vehicle Parts from Vehicle,Parking Lot,28205,1.0,Vehicle Tag,Vehicles and Parts,43931,NaN,NaN,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20120616154500,Theft of Motor Vehicle Parts from Vehicle,Parking Lot,28212,1.0,Vehicle Tag,Vehicles and Parts,38457,NaN,NaN,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20120616154500,Theft of Motor Vehicle Parts from Vehicle,Parking Lot,28212,1.0,Vehicle Tag,Vehicles and Parts,38457,NaN,NaN,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20120616155601,Burglary/B&E,Indoors,28213,1.0,Money/Cash,Money and Securities,37309,NaN,NaN,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198555,20161231235500,Burglary/B&E,Indoors,28208,1.0,TV Equipment,Electronic Equipment and Accessories,34156,NaN,NaN,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198556,20161231235500,Burglary/B&E,Indoors,28208,2.0,TV Equipment,Electronic Equipment and Accessories,34156,NaN,NaN,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198557,20161231235500,Burglary/B&E,Indoors,28208,3.0,Video Game Systems and Accessories,Electronic Equipment and Accessories,34156,NaN,NaN,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198558,20161231235500,Burglary/B&E,Indoors,28208,4.0,Tablet Computer,Electronic Equipment and Accessories,34156,NaN,NaN,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198559,20161231235500,Burglary/B&E,Indoors,28208,5.0,TV Equipment,Electronic Equipment and Accessories,34156,NaN,NaN,...,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
#check if the Incident_datetime is within the weather alert window
crime_weather['in_window'] = (crime_weather['Incident_datetime'] > crime_weather['BEGIN_DATETIME'])
crime_weather[crime_weather['in_window']]

,Complaint_No,Property_Crimes,Location_Type,Zipcode,Property_No,Property_type,Property_Desc,2010 Pop,Workforce Growth,ID Gender,...,END_DATETIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,time_diff,EVENT_TYPE_col,date.1,weather_id,in_window
2732,20120701220002,Shoplifting,Indoors,28216,1.0,Alcoholic Beverage,Consumable Goods,47227,NaN,NaN,...,2012-07-01 17:51:00,35.133333,-80.740767,35.133333,-80.740767,0 days 00:16:00,Hail,2012-07-01,30.0,True
2733,20120701220002,Shoplifting,Indoors,28216,1.0,Alcoholic Beverage,Consumable Goods,47227,NaN,NaN,...,2012-07-01 17:45:00,35.340000,-80.810000,35.340000,-80.810000,0 days 00:15:00,Lightning,2012-07-01,59.0,True
2734,20120701220002,Shoplifting,Indoors,28216,1.0,Alcoholic Beverage,Consumable Goods,47227,NaN,NaN,...,2012-07-01 17:40:00,35.320000,-80.800000,35.180000,-80.655000,0 days 00:19:00,Thunderstorm Wind,2012-07-01,82.0,True
2735,20120701220002,Shoplifting,Indoors,28216,1.0,Alcoholic Beverage,Consumable Goods,47227,NaN,NaN,...,2012-07-01 17:51:00,35.133333,-80.740767,35.133333,-80.740767,0 days 00:16:00,Hail,2012-07-01,30.0,True
2736,20120701220002,Shoplifting,Indoors,28216,1.0,Alcoholic Beverage,Consumable Goods,47227,NaN,NaN,...,2012-07-01 17:45:00,35.340000,-80.810000,35.340000,-80.810000,0 days 00:15:00,Lightning,2012-07-01,59.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196168,20161202144902,Burglary/B&E,Other,28203,1.0,Tools (Power and Hand),Miscellaneous,11315,NaN,NaN,...,2016-11-30 18:29:00,35.124000,-80.953000,35.143000,-80.918000,0 days 00:03:00,Tornado,2016-11-30,135.0,True
196169,20161202144902,Burglary/B&E,Other,28203,2.0,Tools (Power and Hand),Miscellaneous,11315,NaN,NaN,...,2016-11-30 18:29:00,35.124000,-80.953000,35.143000,-80.918000,0 days 00:03:00,Tornado,2016-11-30,135.0,True
196170,20161202144902,Burglary/B&E,Other,28203,3.0,Tools (Power and Hand),Miscellaneous,11315,NaN,NaN,...,2016-11-30 18:29:00,35.124000,-80.953000,35.143000,-80.918000,0 days 00:03:00,Tornado,2016-11-30,135.0,True
196171,20161202144902,Burglary/B&E,Other,28203,4.0,Other,Other Property,11315,NaN,NaN,...,2016-11-30 18:29:00,35.124000,-80.953000,35.143000,-80.918000,0 days 00:03:00,Tornado,2016-11-30,135.0,True
196728,20161208094902,Shoplifting,Indoors,28273,1.0,Other,Other Property,31478,NaN,NaN,...,2016-11-30 18:29:00,35.124000,-80.953000,35.143000,-80.918000,0 days 00:03:00,Tornado,2016-11-30,135.0,True

In [42]:
crime_weather.columns

Index(['Complaint_No', 'Property_Crimes', 'Location_Type', 'Zipcode',
       'Property_No', 'Property_type', 'Property_Desc', '2010 Pop',
       'Workforce Growth', 'ID Gender', 'Median Earnings', 'Race', 'Ethnicity',
       'Incident_datetime', 'DATE', 'EVENT_TYPE', 'date', 'BEGIN_DATETIME',
       'END_DATETIME', 'BEGIN_LAT', 'BEGIN_LON', 'END_LAT', 'END_LON',
       'time_diff', 'EVENT_TYPE_col', 'date.1', 'weather_id', 'in_window'],
      dtype='object')

In [43]:
crime_weather.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 198560 entries, 0 to 198559
Data columns (total 28 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Complaint_No       198560 non-null  int64
 1   Property_Crimes    198560 non-null  object
 2   Location_Type      198560 non-null  object
 3   Zipcode            198560 non-null  int64
 4   Property_No        197290 non-null  float64
 5   Property_type      197290 non-null  object
 6   Property_Desc      197290 non-null  object
 7   2010 Pop           198560 non-null  int64
 8   Workforce Growth   0 non-null       float64
 9   ID Gender          0 non-null       float64
 10  Median Earnings    0 non-null       float64
 11  Race               0 non-null       float64
 12  Ethnicity          0 non-null       float64
 13  Incident_datetime  198560 non-null  datetime64[ns]
 14  DATE               198560 non-null  object
 15  EVENT_TYPE         12716 non-null   object
 16  date               12716 non-null   object
 17  BEGIN_DATETIME     12716 non-null   datetime64[ns]
 18  END_DATETIME       12716 non-null   datetime64[ns]
 19  BEGIN_LAT          12716 non-null   float64
 20  BEGIN_LON          12716 non-null   float64
 21  END_LAT            12716 non-null   float64
 22  END_LON            12716 non-null   float64
 23  time_diff          12716 non-null   object
 24  EVENT_TYPE_col     12716 non-null   object
 25  date.1             12716 non-null   object
 26  weather_id         12716 non-null   float64
 27  in_window          198560 non-null  bool
dtypes: bool(1), datetime64[ns](3), float64(11), int64(3), object(10)
memory usage: 42.6+ MB

In [44]:
crime_weather.drop(['date','date.1','EVENT_TYPE_col','Incident_datetime','BEGIN_DATETIME','END_DATETIME'], axis=1, inplace=True)
crime_weather.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 198560 entries, 0 to 198559
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Complaint_No      198560 non-null  int64
 1   Property_Crimes   198560 non-null  object
 2   Location_Type     198560 non-null  object
 3   Zipcode           198560 non-null  int64
 4   Property_No       197290 non-null  float64
 5   Property_type     197290 non-null  object
 6   Property_Desc     197290 non-null  object
 7   2010 Pop          198560 non-null  int64
 8   Workforce Growth  0 non-null       float64
 9   ID Gender         0 non-null       float64
 10  Median Earnings   0 non-null       float64
 11  Race              0 non-null       float64
 12  Ethnicity         0 non-null       float64
 13  DATE              198560 non-null  object
 14  EVENT_TYPE        12716 non-null   object
 15  BEGIN_LAT         12716 non-null   float64
 16  BEGIN_LON         12716 non-null   float64
 17  END_LAT           12716 non-null   float64
 18  END_LON           12716 non-null   float64
 19  time_diff         12716 non-null   object
 20  weather_id        12716 non-null   float64
 21  in_window         198560 non-null  bool
dtypes: bool(1), float64(11), int64(3), object(7)
memory usage: 33.5+ MB

In [45]:
crime_weather.nunique()

Complaint_No        53968
Property_Crimes         6
Location_Type           5
Zipcode                24
Property_No           110
Property_type          63
Property_Desc          13
2010 Pop               24
Workforce Growth        0
ID Gender               0
Median Earnings         0
Race                    0
Ethnicity               0
DATE                 1941
EVENT_TYPE              7
BEGIN_LAT              73
BEGIN_LON              67
END_LAT                63
END_LON                67
time_diff              38
weather_id            107
in_window               2
dtype: int64

In [46]:
crime_weather.drop_duplicates(inplace=True)

In [47]:
crime_weather.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 145774 entries, 0 to 198559
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Complaint_No      145774 non-null  int64
 1   Property_Crimes   145774 non-null  object
 2   Location_Type     145774 non-null  object
 3   Zipcode           145774 non-null  int64
 4   Property_No       144616 non-null  float64
 5   Property_type     144616 non-null  object
 6   Property_Desc     144616 non-null  object
 7   2010 Pop          145774 non-null  int64
 8   Workforce Growth  0 non-null       float64
 9   ID Gender         0 non-null       float64
 10  Median Earnings   0 non-null       float64
 11  Race              0 non-null       float64
 12  Ethnicity         0 non-null       float64
 13  DATE              145774 non-null  object
 14  EVENT_TYPE        8176 non-null    object
 15  BEGIN_LAT         8176 non-null    float64
 16  BEGIN_LON         8176 non-null    float64
 17  END_LAT           8176 non-null    float64
 18  END_LON           8176 non-null    float64
 19  time_diff         8176 non-null    object
 20  weather_id        8176 non-null    float64
 21  in_window         145774 non-null  bool
dtypes: bool(1), float64(11), int64(3), object(7)
memory usage: 24.6+ MB

In [48]:
#if in_window is False, then set EVENT_TYPE to null
crime_weather.loc[crime_weather['in_window'] == False, 'EVENT_TYPE'] = None

In [49]:
#drop in_window column
crime_weather.drop(['in_window'], axis=1, inplace=True)
crime_weather

,Complaint_No,Property_Crimes,Location_Type,Zipcode,Property_No,Property_type,Property_Desc,2010 Pop,Workforce Growth,ID Gender,...,Race,Ethnicity,DATE,EVENT_TYPE,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,time_diff,weather_id
0,20120616144400,Theft of Motor Vehicle Parts from Vehicle,Parking Lot,28205,1.0,Vehicle Tag,Vehicles and Parts,43931,NaN,NaN,...,NaN,NaN,2012-06-15,None,NaN,NaN,NaN,NaN,NaN,NaN
2,20120616154500,Theft of Motor Vehicle Parts from Vehicle,Parking Lot,28212,1.0,Vehicle Tag,Vehicles and Parts,38457,NaN,NaN,...,NaN,NaN,2012-06-15,None,NaN,NaN,NaN,NaN,NaN,NaN
4,20120616155601,Burglary/B&E,Indoors,28213,1.0,Money/Cash,Money and Securities,37309,NaN,NaN,...,NaN,NaN,2012-06-16,None,NaN,NaN,NaN,NaN,NaN,NaN
5,20120616155601,Burglary/B&E,Indoors,28213,2.0,Other,Miscellaneous,37309,NaN,NaN,...,NaN,NaN,2012-06-16,None,NaN,NaN,NaN,NaN,NaN,NaN
8,20120616162302,Burglary/B&E,Indoors,28208,1.0,TV Equipment,Electronic Equipment and Accessories,34156,NaN,NaN,...,NaN,NaN,2012-06-16,None,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198555,20161231235500,Burglary/B&E,Indoors,28208,1.0,TV Equipment,Electronic Equipment and Accessories,34156,NaN,NaN,...,NaN,NaN,2016-12-31,None,NaN,NaN,NaN,NaN,NaN,NaN
198556,20161231235500,Burglary/B&E,Indoors,28208,2.0,TV Equipment,Electronic Equipment and Accessories,34156,NaN,NaN,...,NaN,NaN,2016-12-31,None,NaN,NaN,NaN,NaN,NaN,NaN
198557,20161231235500,Burglary/B&E,Indoors,28208,3.0,Video Game Systems and Accessories,Electronic Equipment and Accessories,34156,NaN,NaN,...,NaN,NaN,2016-12-31,None,NaN,NaN,NaN,NaN,NaN,NaN
198558,20161231235500,Burglary/B&E,Indoors,28208,4.0,Tablet Computer,Electronic Equipment and Accessories,34156,NaN,NaN,...,NaN,NaN,2016-12-31,None,NaN,NaN,NaN,NaN,NaN,NaN
198559,20161231235500,Burglary/B&E,Indoors,28208,5.0,TV Equipment,Electronic Equipment and Accessories,34156,NaN,NaN,...,NaN,NaN,2016-12-31,None,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
crime_no_weather = crime_weather[crime_weather['EVENT_TYPE'].isnull()].copy()

In [51]:
crime_extreme_weather = crime_weather[crime_weather['EVENT_TYPE'].notnull()].copy()

In [52]:
#export to csv in Data_files folder
crime_weather.to_csv('crime_weather_all_CLEANED.csv')
crime_no_weather.to_csv('crime_no_weather_CLEANED.csv')
crime_extreme_weather.to_csv('crime_extreme_weather_CLEANED.csv')